### ISSUE TITLE
no possibility for data loading before render?

### ISSUE THREAD

**Issue by wmertens** [electrodejs/deprecated-electrode-redux-router-engine#8]
From what I can tell, there is no way to do an initial render, followed by a wait for the required data to load, followed by the actual render, like would be required by e.g. apollo-client or basically any solution that triggers load events at willMount time.

**Comment by caoyangs** [comment]
Are you talking about client side rendering? Certainly you can load data on `componentWillMount` and any data change will cause a re-render.

**Comment by wmertens** [comment]
Sorry, I mean server-side rendering. In the meantime I saw that the generator uses react-resolver, which AFAICT does the double-render internally. I don't know how to link that up to e.g. apollo-client though…

**Comment by ananavati** [comment]
> re: generator uses react-resolver, which AFAICT does the double-render internally

good question @wmertens In order to solve double rendering we use [electrode-redux-router-engine](https://github.com/electrode-io/electrode-redux-router-engine)

**Comment by caoyangs** [comment]
@wmertens you are right react-resolver does double-render internally, we have changed the generator to use electrode-redux-router-engine, i.e this module.

What's the reason you need double render on server side? Since everything will be rendered again on client side.

**Comment by wmertens** [comment]
Well, if you use components that declare the data they on mount, then you need a double render to send the page with the data to the browser.

On the first render, your URL determines what components will be shown, they are rendered and the render triggers a bunch of data fetches. Then you have to wait until the fetches complete, and finally you render the app again (this time with all the data showing) and you send it to the user with a stringified store.

If you don't do this, the user will only see a bunch of loading views until the js loads.

**Comment by wmertens** [comment]
@ananavati so I don't see a way to perform double rendering with electrode-redux-router-engine…

**Comment by jasonmerino** [comment]
I'm also curious about how I would go about fetching data for a component on the server and then wait to send the rendered component output to the client (browser) until after the data had been fetched and rendered into the component.

In short, I'd like to be able to populate all data needed server side and render it into the page component before serving it to the client.

Is there a way to do this easily?

**Comment by mypark** [comment]
@wmertens did you ever figure out a solution to this?  I'm also using the apollo client and having trouble with sending rendered data to the isomorphic view (I get a bunch of loading views as well).

Also is there a way to pass a context to the render function so that I can pass in the apollo client object?

**Comment by wmertens** [comment]
@mypark no, I'm still using my own setup, I have a working solution (non-Electrode) that I don't want to break just yet :)
